name: aura_call
description: "AURA CALL Frontend"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.2.2
  flutter_webrtc: ^0.12.3
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  flutter_secure_storage: ^10.0.0
  device_info_plus: 10.1.2
  crypto: ^3.0.7
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  proximity_sensor: ^1.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/aura.png"

flutter:
  uses-material-design: true
  assets:
    - assets/aura.png
    - assets/call_background_1.png
    - assets/call_background_2.png
    - assets/call_background_3.png
    - assets/call-connected.ogg
    - assets/call-ended.ogg
    - assets/error-busy-hung.ogg
    - assets/incoming.ogg
    - assets/outgoing.ogg
    - assets/ping.ogg
    - assets/switch-call.ogg

  fonts:
    - family: SourGummy
      fonts:
        - asset: assets/SourGummy-Medium.ttf

flutter_native_splash:
  color: "#000000"
  image: "assets/transparent.png"
  android: true
  ios: true
