-- Create contacts table (User -> User relationship)
CREATE TABLE IF NOT EXISTS public.contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id text NOT NULL, -- The user who adds the contact
    contact_id text NOT NULL, -- The friend's ID
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(owner_id, contact_id)
);

-- Enable RLS
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see their own contacts
-- Policy to verify: check if contact exists
-- (Removed strict RLS for now to avoid current_user_id error)
    -- Note: Since we use custom IDs and anon, strictly we might need to filter by owner_id matching our client-side ID
    -- ideally: USING (true) for now as we don't have strict auth.
    
-- Update policy for loose auth (custom ID based)
DROP POLICY IF EXISTS "Public contacts access" ON public.contacts;
CREATE POLICY "Public contacts access" ON public.contacts
    FOR ALL USING (true) WITH CHECK (true);
